package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
)

const (
	// Signature is the header added to the output
	Signature = `Generated by CAI (Codebase AI Interface)
https://github.com/AfazTech/cai`

	// LLMInstructions provides guidance for AI models consuming this output
	LLMInstructions = `LLM INSTRUCTIONS:
This file contains the complete project structure and the content of all source files.
- The "PROJECT STRUCTURE" section shows the directory tree.
- The "FILES" section lists each file's content, separated by "@@@FILE: filename@@@".
- Use this information to understand the codebase, answer questions, or generate new code.
- Pay attention to file paths, dependencies, and the overall architecture.`

	// TreeDescription introduces the tree section
	TreeDescription = `The following section contains the complete project structure:`

	// FilesDescription introduces the files section
	FilesDescription = `The following section contains the content of project files.
Each file is separated by the following delimiter:`

	// FileDelimiter is the marker used before each file's content
	FileDelimiter = "@@@FILE: %s@@@"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Printf("Usage: %s <directory>\n", os.Args[0])
		os.Exit(1)
	}

	root := os.Args[1]

	// Validate root path
	info, err := os.Stat(root)
	if err != nil {
		fmt.Printf("Error accessing path: %v\n", err)
		os.Exit(1)
	}
	if !info.IsDir() {
		fmt.Println("Error: provided path is not a directory")
		os.Exit(1)
	}

	config, err := LoadConfig(root)
	if err != nil {
		fmt.Println("Error:", err)
		os.Exit(1)
	}

	// Normalize project name to avoid "." or ".." as filename
	projectName := config.Project
	if projectName == "" || projectName == "." || projectName == ".." {
		absPath, err := filepath.Abs(root)
		if err == nil {
			projectName = filepath.Base(absPath)
		}
	}
	if projectName == "" || projectName == "." || projectName == ".." {
		projectName = "project" // ultimate fallback
	}

	// Output file name is derived from project name
	outputName := projectName + ".txt"

	// Add output file to ignore list dynamically
	config.Ignore = append(config.Ignore, outputName)

	// Create output file
	file, err := os.Create(outputName)
	if err != nil {
		fmt.Println("Error:", err)
		os.Exit(1)
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	// Write user description FIRST (if provided)
	if config.Description != "" {
		fmt.Fprintln(writer, config.Description)
		fmt.Fprintln(writer)
	}

	// Write signature
	fmt.Fprintln(writer, Signature)
	fmt.Fprintln(writer)

	// Write LLM instructions
	fmt.Fprintln(writer, LLMInstructions)
	fmt.Fprintln(writer)

	// Write tree
	if config.Tree {
		fmt.Fprintln(writer, TreeDescription)
		fmt.Fprintln(writer)
		fmt.Fprintln(writer, "# PROJECT STRUCTURE")
		fmt.Fprintln(writer)

		if err := BuildTree(writer, root, config); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}
		fmt.Fprintln(writer)
	}

	// Write files
	if config.Files {
		fmt.Fprintln(writer, FilesDescription)
		fmt.Fprintln(writer)

		if err := BuildFiles(writer, root, config); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}
	}

	fmt.Printf("Output saved to %s\n", outputName)
}
