package core

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"strconv"
)

const (
	FileDelimiter = "@@@FILE: %s@@@"
	Signature     = `Generated by CAI (Codebase AI Interface)
https://github.com/AfazTech/cai`

	LLMInstructions = `LLM INSTRUCTIONS:
This file contains the complete project structure and the content of all source files.
- The "PROJECT STRUCTURE" section shows the directory tree.
- The "FILES" section lists each file's content, separated by "@@@FILE: filename@@@".
- Use this information to understand the codebase, answer questions, or generate new code.
- Pay attention to file paths, dependencies, and the overall architecture.`

	TreeDescription   = "The following section contains the complete project structure:"
	FilesDescription  = "The following section contains the content of project files."
)

func Run(args []string) {
	if len(args) < 2 {
		printUsage()
		os.Exit(1)
	}

	cmd := args[1]
	rest := args[2:]

	switch cmd {
	case "init", "i":
		fs := flag.NewFlagSet(cmd, flag.ContinueOnError)
		fs.Parse(rest)
		if fs.NArg() < 1 {
			fmt.Println("need project name")
			os.Exit(1)
		}
		if err := runInit(fs.Arg(0)); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}

	case "set-description", "sd":
		fs := flag.NewFlagSet(cmd, flag.ContinueOnError)
		proj := fs.String("project", "", "project name")
		fs.Parse(rest)
		if fs.NArg() < 1 {
			fmt.Println("need description")
			os.Exit(1)
		}
		if *proj == "" {
			p, err := getCurrentProject()
			if err != nil {
				fmt.Println("Error:", err)
				os.Exit(1)
			}
			*proj = p
		}
		if err := runSetDescription(*proj, fs.Arg(0)); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}

	case "set-size", "ss":
		fs := flag.NewFlagSet(cmd, flag.ContinueOnError)
		proj := fs.String("project", "", "project name")
		fs.Parse(rest)
		if fs.NArg() < 1 {
			fmt.Println("need size in MB")
			os.Exit(1)
		}
		size, err := strconv.Atoi(fs.Arg(0))
		if err != nil || size <= 0 {
			fmt.Println("invalid size")
			os.Exit(1)
		}
		if *proj == "" {
			p, err := getCurrentProject()
			if err != nil {
				fmt.Println("Error:", err)
				os.Exit(1)
			}
			*proj = p
		}
		if err := runSetSize(*proj, size); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}

	case "list-projects", "lp":
		if err := runListProjects(); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}

	case "add-ignore", "ai":
		fs := flag.NewFlagSet(cmd, flag.ContinueOnError)
		proj := fs.String("project", "", "project name")
		fs.Parse(rest)
		if fs.NArg() < 1 {
			fmt.Println("need pattern")
			os.Exit(1)
		}
		if *proj == "" {
			p, err := getCurrentProject()
			if err != nil {
				fmt.Println("Error:", err)
				os.Exit(1)
			}
			*proj = p
		}
		if err := runAddIgnore(*proj, fs.Arg(0)); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}

	case "remove-ignore", "ri":
		fs := flag.NewFlagSet(cmd, flag.ContinueOnError)
		proj := fs.String("project", "", "project name")
		fs.Parse(rest)
		if fs.NArg() < 1 {
			fmt.Println("need pattern")
			os.Exit(1)
		}
		if *proj == "" {
			p, err := getCurrentProject()
			if err != nil {
				fmt.Println("Error:", err)
				os.Exit(1)
			}
			*proj = p
		}
		if err := runRemoveIgnore(*proj, fs.Arg(0)); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}

	case "add-include", "adi":
		fs := flag.NewFlagSet(cmd, flag.ContinueOnError)
		proj := fs.String("project", "", "project name")
		fs.Parse(rest)
		if fs.NArg() < 1 {
			fmt.Println("need pattern")
			os.Exit(1)
		}
		if *proj == "" {
			p, err := getCurrentProject()
			if err != nil {
				fmt.Println("Error:", err)
				os.Exit(1)
			}
			*proj = p
		}
		if err := runAddInclude(*proj, fs.Arg(0)); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}

	case "remove-include", "rmi":
		fs := flag.NewFlagSet(cmd, flag.ContinueOnError)
		proj := fs.String("project", "", "project name")
		fs.Parse(rest)
		if fs.NArg() < 1 {
			fmt.Println("need pattern")
			os.Exit(1)
		}
		if *proj == "" {
			p, err := getCurrentProject()
			if err != nil {
				fmt.Println("Error:", err)
				os.Exit(1)
			}
			*proj = p
		}
		if err := runRemoveInclude(*proj, fs.Arg(0)); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}

	case "add-include-group", "aig":
		fs := flag.NewFlagSet(cmd, flag.ContinueOnError)
		proj := fs.String("project", "", "project name")
		fs.Parse(rest)
		if fs.NArg() < 1 {
			fmt.Println("need group name")
			os.Exit(1)
		}
		if *proj == "" {
			p, err := getCurrentProject()
			if err != nil {
				fmt.Println("Error:", err)
				os.Exit(1)
			}
			*proj = p
		}
		if err := runAddGroup(*proj, fs.Arg(0)); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}

	case "remove-include-group", "rig":
		fs := flag.NewFlagSet(cmd, flag.ContinueOnError)
		proj := fs.String("project", "", "project name")
		fs.Parse(rest)
		if fs.NArg() < 1 {
			fmt.Println("need group name")
			os.Exit(1)
		}
		if *proj == "" {
			p, err := getCurrentProject()
			if err != nil {
				fmt.Println("Error:", err)
				os.Exit(1)
			}
			*proj = p
		}
		if err := runRemoveGroup(*proj, fs.Arg(0)); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}

	default:
		root := cmd
		fs := flag.NewFlagSet("snapshot", flag.ContinueOnError)
		projFlag := fs.String("project", "", "project name")
		fs.Parse(rest)
		runSnapshot(root, *projFlag)
	}
}

func runSnapshot(root string, projectName string) {
	info, err := os.Stat(root)
	if err != nil || !info.IsDir() {
		fmt.Println("Error: invalid directory")
		os.Exit(1)
	}

	cfg, err := LoadProject(projectName)
	if err != nil {
		if projectName == "" {
			names, _ := ListProjectNames()
			found := false
			rootAbs, _ := normalizePath(root)
			for _, n := range names {
				c, _ := LoadProject(n)
				if c.RootPath == rootAbs {
					cfg = c
					found = true
					break
				}
			}
			if !found {
				fmt.Println("Error: no project found. use -project flag or run 'cai init'")
				os.Exit(1)
			}
		} else {
			fmt.Println("Error:", err)
			os.Exit(1)
		}
	}

	maxMB := cfg.MaxSizeMB
	if maxMB <= 0 {
		maxMB = 50
	}
	maxBytes := int64(maxMB) * 1024 * 1024

	outName := cfg.Project + ".txt"
	cfg.Ignore = append(cfg.Ignore, outName)

	file, err := os.Create(outName)
	if err != nil {
		fmt.Println("Error:", err)
		os.Exit(1)
	}
	defer file.Close()

	limited := NewLimitedWriter(file, maxBytes)
	bw := bufio.NewWriter(limited)
	defer bw.Flush()

	if cfg.Description != "" {
		fmt.Fprintln(bw, cfg.Description)
		fmt.Fprintln(bw)
	}
	fmt.Fprintln(bw, Signature)
	fmt.Fprintln(bw)
	fmt.Fprintln(bw, LLMInstructions)
	fmt.Fprintln(bw)

	if cfg.Tree {
		fmt.Fprintln(bw, TreeDescription)
		fmt.Fprintln(bw)
		fmt.Fprintln(bw, "# PROJECT STRUCTURE")
		fmt.Fprintln(bw)
		if err := BuildTree(bw, root, cfg); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}
		fmt.Fprintln(bw)
	}

	if cfg.Files {
		fmt.Fprintln(bw, FilesDescription)
		fmt.Fprintln(bw)
		if err := BuildFiles(bw, root, cfg); err != nil {
			fmt.Println("Error:", err)
			os.Exit(1)
		}
	}

	if err := bw.Flush(); err != nil {
		fmt.Println("Error:", err)
		os.Exit(1)
	}
	if limited.exceeded {
		os.Remove(outName)
		fmt.Printf("Error: output exceeded %d MB. Increase maxSizeMB in config.\n", maxMB)
		os.Exit(1)
	}
	fmt.Printf("Output saved to %s\n", outName)
}

func printUsage() {
	fmt.Printf(`Usage:
  %s <directory>               generate snapshot (auto-detect project)
  %s -project <name> <dir>     use specific project
  %s init <name>               create new project
  %s set-description <text>    update description (short: sd)
  %s set-size <MB>             update max file size (short: ss)
  %s list-projects             show all projects (short: lp)
  %s add-ignore <pattern>      add ignore pattern (short: ai)
  %s remove-ignore <pattern>   remove ignore pattern (short: ri)
  %s add-include <pattern>     add include pattern (short: adi)
  %s remove-include <pattern>  remove include pattern (short: rmi)
  %s add-include-group <name>  add predefined group (short: aig)
  %s remove-include-group <name> remove group (short: rig)
`, os.Args[0], os.Args[0], os.Args[0], os.Args[0],
		os.Args[0], os.Args[0], os.Args[0], os.Args[0],
		os.Args[0], os.Args[0], os.Args[0], os.Args[0],
	)
}
